config/routes.rb
Rails.application.routes.draw do

  get 'send/index'

  resources :buy_orders
  devise_for :users
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id' => 'cart#add'
  post '/cart/' => 'cart#create'
  get 'send' => 'send#index'
  post 'send' => 'send#create'
  
  resources :products
  root 'page#home'
  get 'page/about'
  get 'page/faqs'
  get 'page/contact'

end

app/models/buy_order.rb
class BuyOrder < ActiveRecord::Base
has_many :hasBuyOrders
has_many :products, through: :hasBuyOrders 
after_create :save_products
def products=(value)
		@products=value
		#logger.debug @products
end
def save_products
		@products.each do |product|
		productTemp=product[:product]
		quantity =product[:quantity]
		HasBuyOrder.create(product_id: productTemp.id, buy_order_id: self.id, quantity: quantity)	
		end 
end
end

app/models/has_buy_order.rb
class HasBuyOrder < ActiveRecord::Base
  belongs_to :product
  belongs_to :buyOrder 
  
end

app/models/product.rb
class Product < ActiveRecord::Base

	has_many :hasBuyOrders
	has_many :buyOrders, through: :hasBuyOrders

 	has_attached_file :cover, styles: {thumb:"400x300", mini:"400x200"}
    validates_attachment_content_type :cover, content_type: /\Aimage\/.*\Z/
 

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buy_orders_controller.rb
class BuyOrdersController < ApplicationController
  before_action :set_buy_order, only: [:show, :edit, :update, :destroy]

  # GET /buy_orders
  # GET /buy_orders.json
  def index
    @buy_orders = BuyOrder.all
  end

  # GET /buy_orders/1
  # GET /buy_orders/1.json
  def show
    @quantyties=HasBuyOrder.where("buy_order_id = ?", params[:id])
    logger.debug @quantyties
  end

  # GET /buy_orders/new
  def new
    @buy_order = BuyOrder.new
  end

  # GET /buy_orders/1/edit
  def edit
  end

  # POST /buy_orders
  # POST /buy_orders.json
  def create
    @buy_order = BuyOrder.new(buy_order_params)

    respond_to do |format|
      if @buy_order.save
        format.html { redirect_to @buy_order, notice: 'Buy order was successfully created.' }
        format.json { render :show, status: :created, location: @buy_order }
      else
        format.html { render :new }
        format.json { render json: @buy_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buy_orders/1
  # PATCH/PUT /buy_orders/1.json
  def update
    #logger.debug "Person attributes hash: #{@buy_order.id}"
    respond_to do |format|
      if @buy_order.update(buy_order_params)
        format.html { redirect_to @buy_order, notice: 'Buy order was successfully updated.' }
        format.json { render :show, status: :ok, location: @buy_order }
      else
        format.html { render :edit }
        format.json { render json: @buy_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buy_orders/1
  # DELETE /buy_orders/1.json
  def destroy
    @buy_order.destroy
    respond_to do |format|
      format.html { redirect_to buy_orders_url, notice: 'Buy order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy_order
      @buy_order = BuyOrder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buy_order_params
      params.require(:buy_order).permit(:name, :number_order, :date_delivery, :date_order, :payment)
    end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
before_action :authenticate_user!	


skip_before_action :verify_authenticity_token
	def add
	  	id = params[:id]

		  	if session[:cart] then
		  		cart = session[:cart]
			else
				session[:cart] = {}
				cart = session[:cart]
		  	end
		  	
		  	if cart[id] then
			   cart[id] = cart[id] + 1
			else
				cart[id] = 1
		  	end
	  	redirect_to :action => :index
	end

	def clearCart
		session[:cart] = nil
		@products = nil
		redirect_to :action => :index	
	end

  def index
	  	if session[:cart] then
	  		build_cart
		else  
	  		@cart = {}
	  		@products =[]

	  	end
	  	#logger.debug @products
  end
   
   def create
   	@buyOrder=BuyOrder.new
   	build_cart
   	#logger.debug @products
   	@buyOrder.products=@products
   	time = Time.now
	date_str=time.to_formatted_s(:short)
   	@buyOrder.name=current_user.email+"_"+date_str
   	@buyOrder.date_order=Time.now

   

   #logger.debug @buyOrder.products
   	if @buyOrder.save
   		redirect_to @buyOrder
	end

   end
private
 def build_cart
	if session[:cart] then
	  		@cart = session[:cart]
	  		@products =[]
	  		@cart.each do | id, quantity|
				@products<<{ product: Product.find_by_id(id),quantity: quantity}
			end
   end
end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
before_action :authenticate_user!, only: [:contact]	

  def home
  end

  def about
  end

  def faqs
  end

  def contact
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'El producto fue creado.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'El producto fue actualizado.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'El producto fue destruido.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:title, :description, :image_url, :price, :category, :subcategory, :cover)
    end
end

app/controllers/send_controller.rb
class SendController < ApplicationController
  
  def index
  end

  def create 
  	 @params = params
	 ContactMailer.contact_send(params).deliver
	 flash[:notice]= "Formulario Enviado."
	 redirect_to send_path
  end
	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buy_orders_helper.rb
module BuyOrdersHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/send_helper.rb
module SendHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/buy_orders/_form.html.erb
<%= form_for(@buy_order) do |f| %>
  <% if @buy_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buy_order.errors.count, "error") %> prohibited this buy_order from being saved:</h2>

      <ul>
      <% @buy_order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :number_order %><br>
    <%= f.text_field :number_order %>
  </div>
  <div class="field">
    <%= f.label :date_delivery %><br>
    <%= f.date_select :date_delivery %>
  </div>
  <div class="field">
    <%= f.label :date_order %><br>
    <%= f.date_select :date_order %>
  </div>
  <div class="field">
    <%= f.label :payment %><br>
    <%= f.check_box :payment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buy_orders/edit.html.erb
<h1>Editing Buy Order</h1>

<%= render 'form' %>

<%= link_to 'Show', @buy_order %> |
<%= link_to 'Back', buy_orders_path %>

app/views/buy_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Buy Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number order</th>
      <th>Date delivery</th>
      <th>Date order</th>
      <th>Payment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buy_orders.each do |buy_order| %>
      <tr>
        <td><%= buy_order.name %></td>
        <td><%= buy_order.number_order %></td>
        <td><%= buy_order.date_delivery %></td>
        <td><%= buy_order.date_order %></td>
        <td><%= buy_order.payment %></td>
        <td><%= link_to 'Show', buy_order %></td>
        <td><%= link_to 'Edit', edit_buy_order_path(buy_order) %></td>
        <td><%= link_to 'Destroy', buy_order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buy order', new_buy_order_path %>

app/views/buy_orders/new.html.erb
<h1>New Buy Order</h1>

<%= render 'form' %>

<%= link_to 'Back', buy_orders_path %>

app/views/buy_orders/show.html.erb
<div class="container ">
  <div class="row">
    <div class="container">
      <div class="col-xs-12">
        <div>
              <h4>
              <strong>Name:</strong>
              <%= @buy_order.name %>
              </h4>

              <h4>
              <strong>Number order:</strong>
              <%= @buy_order.number_order %>
              </h4>

              <h4>
              <strong>Date delivery:</strong>
              <%= @buy_order.date_delivery %>
              </h4>

              <h4>
              <strong>Date order:</strong>
              <%= @buy_order.date_order %>
              </h4>

              <h4>
              <strong>Payment:</strong>
              <%= @buy_order.payment ? 'Pagado' : 'Pendiente'%>
              </h4>
              <br><br>
              <% total = 0 %>

              <p id="notice"><%= notice %></h4>
        </div>
      </div>


      <div  class="list-inline" >
        <% @buy_order.products.each do |product| %>
        <li class="col-xs-6">
          <div class="col-xs-12">
            <div class="col-xs-5">
    
              <h4><%= product.title %></h4> 
              <!-- <h4><%= product.description %></h4> -->
              <h4><%= number_to_currency(product.price, :unit =>'$') %></h4>

              <% @quantyties.each do |hasBuyOrder| %>
                <% if product.id==hasBuyOrder.product_id %>
                   <h4>Cantidad: <%=hasBuyOrder.quantity %></h4>    
                    <p>
                      <%total+=hasBuyOrder.quantity*product.price%>
                    </p>
                <%end%>
              <%end%>
            </div>
            <div class="col-xs-7">  
              <%= image_tag product.cover.url(:thumb), class:"col-xs-12"%>
            </div>
          </div>

          <br>
        <%end%>
        </li> 
      </div>


      <div class="col-xs-12"> 
        <div class="text-center">
          <h4>Total a pagar: <br><%=number_to_currency(total,:unit =>'$')%><br></h4>
        </div>
        <br>
        <%= form_for(@buy_order) do |f| %>
          <% if @buy_order.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@buy_order.errors.count, "error") %> prohibited this buy_order from being saved:</h2>
              <ul>
                <% @buy_order.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>
          <div class="field" style="display:none" >
            <%= f.label :payment %><br>
            <%= f.check_box :payment, {:checked=>true}%>
          </div>
          <div class="field" style="display:none">
            <%= f.label :date_delivery %><br>
            <%= f.date_select :date_delivery %>
          </div>
          <% unless @buy_order.payment?%>
            <div class="actions text-center">
              <%= f.submit "Pagar", class:"btn btn-info btn-lg text-center" %>
            </div>          
          <%end%>
        <%end%>
        <br>
        <div class="text-center">
          <%= link_to 'Regresar', buy_orders_path, class:"btn btn-info text-center"  %>      
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cart/index.html.erb
<div class="box">
<h1 class="text-center col-xs-12">Mi Carrito</h1>
</div> 

<div class="text-center">
<% if @cart.empty? %>
	<h2>Tu carrito esta vacio</h2>
<% else %>
	<%= link_to 'Limpiar Carrito', cart_clear_path, class:"btn btn-primary text-center blanco" %>
<%end%>
</div>
<% total = 0 %>

<ul class="col-xs-12">
	<div class="col-xs-12 col-md-6">
		<li class="container">
			<% @products.each do | product | %>
			<div class"col-md-12" >
				<%productTemp=product[:product] %>
					<div class"col-xs-6">
						<div class="col-md-6 ">
							<%= image_tag productTemp.cover.url(:thumb), class:"img col-xs-12" %>
						</div>
						<div class=" ">
							<h3><%= link_to productTemp.title, productTemp%></h3>					
	                       <%= truncate(productTemp.description, length:300,escape:false) %>

               				<%=  %>
									
							<div class="list-inline text-center ">
							<%quantity =product[:quantity]%>
	 						<h4>
	 							<%= number_to_currency(productTemp.price, :unit =>'$')  %>
								| Cantidad: <%=quantity%> 						
	 						</h4>								
						</div>
					</div>
				</div>
			</div>
			<br><br><br>
		</li>		

<%=@cart.length + quantity -1 %>			


			<%total+=quantity*productTemp.price%>
		<% end %>
	</div>
	<div class="col-xs-12 col-md-6 text-right">
		<div class=" text-center">
			<p><b><%=number_to_currency(total,:unit =>'$')%></b></p>
			<% if user_signed_in?%>

			<% if @cart.empty? %>			
				<form  action="/products" >
					<input type="submit" value="Seguir comprando" , class="btn btn-primary text-center blanco">
				</form>
			<% else %>			
				<%= link_to 'Seguir comprando', products_path %>
			<% end %>
			<%end%>
			<br><br>

			<% if @cart.empty? %>
				<p></p>
			<% else %>
				<form accept-charset="UTF-8" action="/cart" method="post">
					<input type="submit" value="Confirmar compra" , class="btn btn-primary text-center blanco">
				</form>
			<%end%>
		</div>		
	</div>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cartapp</title>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="nav">

    <div class="page_nav">
		<%= link_to "Shop", products_path %>

		<div class="collapse navbar-collapse col-sm-12" >
			<%= link_to "Home", root_path %>
			<%= link_to "Informacion", page_about_path %>
			<!-- <%= link_to "FAQs", page_faqs_path %> -->
			<%= link_to "Contacto", send_index_path %>
		</div>
	</div>
 	<div id="sign_in"> 


	<% if user_signed_in?%>
		<%= link_to "Salir", destroy_user_session_path, method: :delete %>
	<% else %>
		<%= link_to "Entrar", new_user_session_path %>
		<%= link_to "Crear Cuenta", new_user_registration_path %>
	<% end %>

	<% if user_signed_in?%>
        <a class="thumb pull-left img-responsive" href="/cart">
            <button type="button" class="btn btn-default" aria-label="Left Align">
                <span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>
					<% if session[:cart] then%>
						<%=session[:cart].length  %>
					<%else %>
						0
					<%end%>	
            </button>                    
        </a>
    <% end %>  
	</div>	
</nav>

<div class="main_wrap">
	<div class="row jumbotron main">

		<%= yield %>
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>
	</div>	
</div>	



<footer class="footer  bs-docs-footer ">
    <div class=" ">     
    	<div class="visible-xs f col-xs-12 col-sm-1  " >
        <ul class=" list-inline text-right ">
             
             <li><%= link_to "Home", root_path, class:"blanco" %></li>
             <li><%= link_to "Informacion", page_about_path, class:"blanco" %></li>
            <!-- <li><%= link_to "FAQs", page_faqs_path, class:"blanco" %></li> -->
             <li><%= link_to "Contacto", send_index_path, class:"blanco" %></li>
             
        </ul>
    	</div>
    </div>
</footer>


</body>
</html>

app/views/page/about.html.erb
<h1>About</h1>

app/views/page/contact.html.erb
<h1>Contact</h1>

app/views/page/faqs.html.erb
<h1>FAQs</h1>

app/views/page/home.html.erb
<h1>Home</h1>

app/views/products/_form.html.erb
<div class="">
  <div cloass="container ">
    <div class="text-center ">
      <div class="main-container">
        <div class="box form-group col-xs-12">    
          <%= form_for(@product) do |f| %>
            <% if @product.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
                <ul>
                <% @product.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
                </ul>
              </div>
            <% end %>
            <div class="col-xs-12">
              <div class="form-group col-md-3">
                <%= f.label :title %><br>
                <%= f.text_field :title, class:"form-control" %>
              </div>

              <div class="form-group col-md-9">
                <%= f.label :description %><br>
                <%= f.text_area :description, class:"form-control area" %>
              </div>
            </div>

            <div class="col-xs-12">
              <div class="form-group col-xs-6">
                <%= f.label :Imagen %><br>
                <%= f.file_field :cover, class:"form-control" %>
              </div>

              <div class="form-group col-xs-6">
                <%= f.label :price %><br>
                <%= f.number_field :price, class:"form-control" %>
              </div>
            </div>

            <div class="col-xs-12">
              <div class="form-group col-xs-6">
                <%= f.label :category %><br>
                <%= f.text_field :category, class:"form-control" %>
              </div>

              <div class="form-group col-xs-6">
                <%= f.label :subcategory %><br>
                <%= f.text_field :subcategory, class:"form-control" %>
              </div>
            </div>

            <div class="text-center box ">
              <%= f.submit "Gardar cambios",class:"btn btn-primary btn-xs"%>
            </div>    
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div>
	<div class="box">
		<h1 class="text-center col-xs-12">Editar Producto</h1>
	</div>

	<div>
	<%= render 'form' %>	
	</div>
 
<div class="text-center">
	<div class="btn btn-primary btn-xs ">	
		<%= link_to 'Ver', @product, class:"blanco" %> |
		<%= link_to 'Regresar', products_path,class:"blanco" %>
	</div>    	
</div >

	
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
  <div class="container col-xs-12">
    <div class="text-center">
      <% if user_signed_in?%>
        <%if current_user.admin? %>
          <h4><%= link_to 'Nuevo Producto', new_product_path %></h4> 
        <%end%>
      <%end%>
    </div>
  </div>
  <div class="box">
    <h1 class="text-center col-xs-12">Productos</h1>
  </div> 
  <div cloass="container ">
    <div class="text-center ">
      <div class="main-container">
        <div class="box">
          <% @products.each do |product| %>
            <div class="col-xs-12 col-sm-6 col-md-4  margen">
              <div class="box margen text-left">
                <div class=" ">
                    <%if product.cover?%>
                      <%= image_tag product.cover.url, class:"col-xs-6" %>
                    <% else %>
                     <td></td> 
                    <% end %>                          
                </div>
                <div class=""> 
                  <div>
                    <h4>
                       <%= link_to product.title ,product, class:"titulo " %>
                    </h4>
                    <p class="text-description">
                       <%= truncate(product.description, length:100,escape:false) %>
                    <p>
                  </div>
                  <div>
                    <h4>
                       $<%= product.price %>
                    </h4>
                  </div>
                  <!--   
                     <div>
                              <h4>Categoria:</h4> 
                            <p>
                               <%= product.category %> 
                            </p>
                          </div>

                          <div>
                            <h4>Subcategoria:</h4> 
                            <p>
                              <%= product.subcategory %>
                            </p>
                          </div>
                  -->        

                  <div class="list-inline ">
                    <% if user_signed_in?%>
                      <%if current_user.admin? %>
                        <li><%= link_to 'Editar', edit_product_path(product) %></li>
                        <li><%= link_to 'Eliminar', product, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                      <%end%>
                    <%end%>
                  </div>

                  <div class="">
                    <h4><a href="/cart/<%= product.id %>"> Agregar al carrito</a></h4>  
                  </div> 
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>  
  </div>

                       

                      

app/views/products/new.html.erb
<div>

	<div class="box">
		<h1 class="text-center col-xs-12">Nuevo Producto</h1>	
	</div>

	<div>
		<%= render 'form' %>	
	</div>
	<div class="text-center">

		<div class="btn btn-primary btn-xs ">	
			<%= link_to 'Regresar', products_path,class:"blanco" %>
		</div>
	</div>
	
</div>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
  <div class="text-right ">
    <div class="btn btn-info btn-e-r ">
      <% if user_signed_in?%>
        <%if current_user.admin? %>
          <%= link_to 'Editar', edit_product_path(@product) %> |
        <%end%>
      <%end%>  
      <%= link_to 'Regresar', products_path %>
    </div>    
  </div>
            
  <div class="box">
    <h1 class="text-center col-xs-12"><%= @product.title %></h1>
  </div> 
  <div cloass="container ">
    <div class="text-center ">
      <div class="main-container">
        <div class="box">
          <div class="col-xs-12 col-sm-6 " >
            <%if @product.cover?%>
              <%= image_tag @product.cover.url , class:"col-xs-12 "%>   
            <% else %>
              <td></td> 
            <% end %>             
          </div>        
          <p class="description-2 text-left">
            <%= @product.description %>    
          </p>
<br><br>
          <p class="text-left">
            <strong><%= number_to_currency @product.price %></strong>
          </p>
<br><br>
          <div class="list-inline">
            <li>
              <p>
                Category:
                <strong><%= @product.category %></strong>              
              </p>
            </li>
            <li>
              <p>
                Subcategory:
                <strong><%= @product.subcategory %></strong>              
              </p>
            </li>
          </div>
          <div class="btn btn-primary">
            <h4><a href="/cart/<%= @product.id%>" id="cart_content" class="blanco text-center"> Agregar al carrito</a></h4>  
          </div>        
          <div id="cart_content"></div>

        </div>
      </div>
    </div>  
  </div>

app/views/send/index.html.erb
  <div class="main-container col-xs-12">
    <div class="box">
      <div classs="" >
        <h1 class="text-center col-xs-12">Contacto</h1>
      </div> 
      <div cloass="container form-group ">
        <div class="text-left ">
          <div class="main-container col-xs-12 ">

			<%= form_tag send_path,method: :post do %>

			<div class="form-group col-sm-6 text-inline">
			<%= label_tag :name,'Nombre'%><br/>
			<%= text_field_tag :name,""  , class:"form-control " %> <br/>
				
			</div>


			<div class="form-group col-sm-6 text-inline">
			<%= label_tag :email, 'Email'%> <br/>
			<%= text_field_tag :email,"", class:"form-control " %> <br/>
				
			</div>


			<div class="form-group col-sm-6 text-inline">
			<%= label_tag :subject, 'Asunto'%> <br/>
			<%= text_field_tag :subject,"" , class:"form-control "%> <br/>
				
			</div>

			<div class="form-group col-sm-6 text-inline">
			<%= label_tag :content, 'Contenido'%><br/>
			<%= text_area_tag :content,"" , class:"form-control "%> <br/>
				
			</div>


			<div class="form-group form-inline text-inline">
			<%= submit_tag 'Enviar', class:"form-control "%>
				
			</div>

			<% end %>


         </div>  
        </div>
      </div>
    </div>
  </div>
</div>